language: erlang
otp_release:
  - 19.1
  - 19.0
  - 18.2.1
  - 18.1
  - 18.0
script: "rm -rf .git && make tests"
services:
  - mongodb
addons:
apt:
  sources:
    - mongodb-3.0-precise
  packages:
    - mongodb-org-server